dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "pDZdYy4Be4JGHgh13vWTqVOHoy+7TIAOZHoznlxHu3dlvvp8UwB2Cjuvid4hal2bNCpUNVLhOgBxNzmJ/Voc7SXDe
R3gonLN38QmmCQJTSyahEXZTEu6tOXnvsQc1PtWrlPI2MBGFNNSoBUYOjo+MSwW3kP/+2tqa0TZsS1SChSYraS3v9pPZAG9cLYhd
+ACVfk+4BrvUiaKhQ3vhjs1oKiLSXtXG7C1rcXbPLTPUtq2WWK12ZUCx0GPIo0BCMlNmZZ5oE0uub0iXZvY2GTQ/lR1NRpwowB79
/YwrAnw5/BLLS09P0NVUm9m5w91rjwIPP5wjaRLj8q/53Dqmh5WZh+otE7x8PrtM/5FlA4xcHULX1/gJIMp4rYVQZx1VLtSgtrTL
9e33tqGFaiI75kVYuauOGHItXaa3F/VUwW0Vqn0i0brUqBJhG1hTq+SNrfJ8aOBfFCHHQdzr0Q1QWTnm4V1jqlqm+7ALTiVQVwoA
ZJBjaIIH4WmAxYpxlhS+iVYn/czv45Bz8WC+bj+clmdmddxnseFaQtUkNCBCEtQU5t/OeUUR9J5eGWY7COGNzbLaJRDlDR5BI262
+FvLIHytCMC67REcFwUrtXQaWVuDuuf8rbhuwGjDXPA58N0jkDVMe/B3pBMuCwY4L59BRCszeR5SPXwCux+dxGgrfPGJ44="
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: oraclejdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk12
      script:
        - mvn test -B
